// src/eventData.js
export const events = [
  {
    id: "event1",
    title: "Fitverse Launch Run",
    startDate: "05-01-2025",
    endDate: "05-01-2025",
    mode: "In-Person (Sample City)",
    description: "Kick off the year with our community fitness run.",
    image: "/images/event1.jpg",
    link: "/event1",
  },
  {
    id: "event2",
    title: "Virtual Yoga Weekend",
    startDate: "15-02-2025",
    endDate: "16-02-2025",
    mode: "Online Sessions",
    description: "Relax and recharge with guided yoga and meditation sessions.",
    image: "/images/event2.jpg",
    link: "/event2",
  },
  {
    id: "event3",
    title: "Spring Wellness Fair",
    startDate: "23-03-2025",
    endDate: "23-03-2025",
    mode: "In-Person (Sample City)",
    description: "A full-day wellness fair with workshops, talks, and activities.",
    image: "/images/event3.jpg",
    link: "/event3",
  },
  {
    id: "event4",
    title: "Community Walkathon",
    startDate: "10-04-2025",
    endDate: "10-04-2025",
    mode: "In-Person (Sample City)",
    description: "Walk together for health and community spirit.",
    image: "/images/event4.jpg",
    link: "/event4",
  },
  {
    id: "event5",
    title: "Summer Fitness Challenge",
    startDate: "01-06-2025",
    endDate: "30-06-2025",
    mode: "Online & In-Person",
    description: "A 30-day challenge with daily workouts and progress tracking.",
    image: "/images/event5.jpg",
    link: "/event5",
  },
  {
    id: "event6",
    title: "Evening Zumba Party",
    startDate: "12-07-2025",
    endDate: "12-07-2025",
    mode: "In-Person (Sample City)",
    description: "Dance, sweat, and have fun in this high-energy Zumba event.",
    image: "/images/event6.jpg",
    link: "/event6",
  },
  {
    id: "event7",
    title: "Mindfulness Retreat",
    startDate: "20-08-2025",
    endDate: "22-08-2025",
    mode: "In-Person (Sample Hills)",
    description: "A 3-day retreat focusing on meditation, breathing, and self-care.",
    image: "/images/event7.jpg",
    link: "/event7",
  },
];
